### PR TITLE
[DO NOT MERGE] single build.sh + Makefile for scotch + ptscotch

### PR DESCRIPTION
**Pull request by minrk**
builds on #16

- single build.sh for both scotch and ptscotch
- move CFLAGS/etc. logic to build.sh, which is much simpler than conditionals in Makefile
- remove unused pthread patch for case that's not relevant
- run mpi tests on Darwin, working around mpich O_NONBLOCK error

This build.sh and Make.inc can be used exactly as-is on master

### CODE REVIEW

**Comment by dalcinl** [comment]
Why you removed patch2? If we (or others) ever want to build without thread support, we need that patch. What's the harm of keeping it?

**Comment by dalcinl** [comment]
@minrk Could you please wait until I can finish to work in some other issues in #16, then you can take over and do whatever refactor (like moving logics from make to bash)? 

I have the feeling that we are stepping over each other without proper discussion.

* We have agreed that scotch should enable threads, and ptscotch should not. Good.
* What about the provided headers and libraries? Should ptscotch provide sequential+parallel headers/librareis, or just the parallel ones?
* Is your on-noblock trick is supposed to work both on Circle-CI and Travis-CI?

**Comment by dalcinl** [comment]
@minrk When you "make ptesmumps", you get almost all sequential+parallel headers and libraries, EXCEPT that the sequential `libesmumps.a` is not there, and then PETSc fails to configure.

**Comment by minrk** [comment]
Isn’t that a bug in petsc configuration if it fails to configure when serial scotch isn’t present, and it’s supposed to use ptscotch?

**Comment by minrk** [comment]
I’ll stop working on this until you are done.  I removed the unused threads patch because it only applies to a case that isn’t relevant: pthreads being *unavailable*. That doesn’t occur for conda-forge, so I wanted to keep the deviations from upstream minimal.

I expected the noblock patch to work on circle, but it doesn’t appear to, so we are still stuck not testing on Linux.

**Comment by dalcinl** [comment]
Perhaps the issue in PETSc with `libesmumps.a` is actually a bug, but remember that supports `--download-xxx` other packages that depend on SCOTCH/PTSCOTCH, so maybe PETSc is just being picky and checking for the full thing. I'll ask upstream.

**Comment by dalcinl** [comment]
@minrk about the thread patch, I was thinking on users that for any reason may need to do a manual, local rebuild of this package with pthreads disabled. They could just grab our recipe and do minimal modifications to achieve that goal (in my original `Makefile.inc`, that can be done by just setting `pthread = 0`). Given that the patch does no harm to our build, and it might be useful for others, that's the reason I  decided to grab it from PETSc's custom scotch repo.

**Comment by dalcinl** [comment]
@minrk I'm almost done with #16. Note the different build install path for ptscotch, now the ptscotch package only contains the parallel headers and libraries. So, in short, the files provided by scotch and ptscotch are disjoint sets.

The only issue that remains is the header `epsmumps.h`, right now the ptscotch package does not provide it, but it do provide `libptesmumps.a`. I'm not sure what to do about it. Maybe ship it anyway? What conda does if two packages provide the same file are are installed together?

**Comment by dalcinl** [comment]
About the configure logics in `build.sh`, maybe we could add all that in a separate `config.sh` script and then `source $RECIPE_DIR/config.sh` at the beginning of `build.sh` ?

**Comment by minrk** [comment]
Thanks! #18 applies this PR to master, plus moving the logic to build.sh. I didn't end up adding a config.sh since configuring the build is already what build.sh is for, and moving a couple of lines to a different script only to source it didn't make a lot of sense to me.

> Maybe ship it anyway? What conda does if two packages provide the same file are are installed together?

conda doesn't check for conflicts, so I think whatever package happens to get installed last will own the file. If it's the *same* file, then it makes sense for it to be in scotch and for ptscotch to depend on scotch, right?

**Pull request closed without merging**
