### PR TITLE
restore mpiexec tests on Darwin

### PR DESCRIPTION
**Pull request by minrk**
still can't run on Linux due to O_NONBLOCK issues

### CODE REVIEW

**Comment by minrk** [comment]
taking a stab at a solution that might work on Linux

**Comment by minrk** [comment]
indeed it does work

**Comment by dalcinl** [comment]
@minrk Out of curiosity, wouldn't this be better for `stdin` redirection? 

```
mpiexec $@ 2>&1 </dev/null | cat
```

**Comment by minrk** [comment]
Sure. It doesn't matter too much, I think, but that's a good idea.

**Comment by dalcinl** [comment]
@minrk Any clue why the uploads from Travis-CI are not working?

**Comment by minrk** [comment]
There was an issue earlier where anaconda tokens had to be reissued. It was applied to master but not the ptscotch branch. #22 fixed it and now the latest build has been uploaded.

**Pull request merged**
