### PR TITLE
Fix and simplify build and rerender

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by basnijholt** [comment]
Thanks for this work!

What did change in the Makefiles exactly?

**Comment by minrk** [comment]
Looks like Linux didn't change, but it was reformatted a bit.

Mac added:

```
CLIBFLAGS       = -fPIC
```

and changed `-lpthread` to `-pthread`

and added `-DIDXSIZE64`

**Comment by dalcinl** [comment]
I have bad whitespace in one of the makefiles, sorry.

**Comment by dalcinl** [comment]
I fixed the bad whitespace. @minrk is correct. Aside from the renames, I fixed the macOS build. The macOS makefile is now almost identical to the Linux one, with extra flags at the end of the line. Eventually, we may refactor things to have a single `Makefile.inc`.

FYI, I'm working on a new recipe for a `ptscotch` package, as this is blocking the build of the `petsc` package. The new `ptscotch` package will depend on `scotch` and only provide the libs and headers corresponding to the parallel variant.

**Comment by dalcinl** [comment]
@basnijholt @minrk Folks, BTW, is there any good reason we don't ship this package with shared libraries? It may require some little work, but I think we should do it. Thoughts?

**Comment by basnijholt** [comment]
I guess the reason is simple: no one took the effort to do it. If you have the time and know how to do it, that would be great!

**Comment by dalcinl** [comment]
@basnijholt @minrk Folks, I don't know yet all the gory details of registering in GitHub and CI services. Could you please do it for me for the new ptscotch package?

https://github.com/dalcinl/ptscotch-feedstock

**Comment by basnijholt** [comment]
Ah, sure!

But it's quite simple:
* fork [this](repo)
* add your recipe there
* make a (PR)[https://github.com/conda-forge/staged-recipes/pulls] here

and then everything will happen by itself :)

**Comment by dalcinl** [comment]
@basnijholt Sorry, but I'm not following your *fork this* step. Do you mean the `conda-forge/staged-recipes` repo?

**Comment by basnijholt** [comment]
Exactly, (there was a typo, sorry)!

**Comment by dalcinl** [comment]
Folks, I think this one is ready to go. Next step is conda-forge/staged-recipes#4126.

**Comment by basnijholt** [comment]
Perfect, thanks a lot!

**Pull request merged**
