### PR TITLE
add version 6.1.3

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
I wonder if it would be better to run `make clean` after building esmumps

**Comment by Tobias-Fischer** [comment]
I think the magic `sleep 1` that @traversaro introduced is gone in the updated patch. I think adding this back in might do the job? @traversaro might be able to enlighten us - the issue we're seeing is:
```
x86_64-apple-darwin13.4.0-clang -shared -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniforge3/conda-bld/scotch-pkgs_1646864243342/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/Users/runner/miniforge3/conda-bld/scotch-pkgs_1646864243342/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -lm -lz -pthread -lm -lz -pthread -Wl,-install_name,@rpath/libptscotcherr-6..dylib library_error_pt.o -o libptscotcherr-6...dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
  "_MPI_Comm_rank", referenced from:
      _SCOTCH_errorPrint in library_error_pt.o
      _SCOTCH_errorPrintW in library_error_pt.o
  "_MPI_Initialized", referenced from:
      _SCOTCH_errorPrint in library_error_pt.o
      _SCOTCH_errorPrintW in library_error_pt.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by Tobias-Fischer** [comment]
Nice - this seems to have done the trick :).

**Review by Tobias-Fischer — APPROVED** [review]

**Review by basnijholt — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Fix #68

**Pull request merged**
