### PR TITLE
add impi build for Windows

### PR DESCRIPTION
**Pull request by minrk**
who knows if this will work! May be needed for dolfinx

### CODE REVIEW

**Comment by dalcinl** [comment]
Maybe CMake's `FindMPI.cmake` is not really prepared to cope with the Intel MPI install layout within a conda environment? This is going to be very hard to debug on CI.

**Comment by minrk** [comment]
Yeah, I think you're right. I'm not sure what args are going to be needed

**Comment by dalcinl** [comment]
Intel MPI on Windows with CMake is definitely working, otherwise mpi4py with the scikit-build-core backend would not work [[link]](https://github.com/mpi4py/mpi4py/actions/runs/9144689791/job/25142806166). However, these build tests are using Intel MPI installed in the usual `%ProgramFiles%` prefix, and not a conda environment.  Also, the thing is running on GHA, not Azure.

**Comment by minrk** [comment]
build with 46c80c78c0408cf09101286b3eadd2258c161023 actually succeeded, now just working on removing excessive config, since I'm sure I specified far more than needed

**Comment by minrk** [comment]
turns out, just needed to set include, lib and it works fine:

```
-D MPI_C_ADDITIONAL_INCLUDE_DIRS=%LIBRARY_PREFIX%\include
-D MPI_C_LIBRARIES=impi
```

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Thanks @minrk - Lgtm!

**Pull request merged**
