### PR TITLE
7.0.5

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by minrk** [comment]
Does this change the ABI? If so, we'll need to make sure the new builds are not accepted as a dependency for anything built against the old ones (possibly via repodata patches), and may need to add a build variant matrix if there's a reason to keep both.

**Comment by looooo** [comment]
I think so. Maybe someone with more expertise can comment on this.

**Comment by Tobias-Fischer** [comment]
An easy way to get around potential ABI issues is to bump the version to 7.0.5 in this PR (see #89)

**Comment by looooo** [comment]
seems like some patches need to be realigned:
```
Applying patch: /home/conda/recipe_root/0001-Remove-unconditional-testing.patch with args:
['-Np1', '-i', '/tmp/tmp_3no25ar/0001-Remove-unconditional-testing.patch.native', '--binary']
checking file CMakeLists.txt
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
Warning: failed to download source
```

**Comment by Tobias-Fischer** [comment]
I've started giving this a go, but I don't have time to resolve the remaining issues, apologies.

@minrk @looooo - do you have capacity to look into this? I might have deleted too many of the old patches.

**Comment by minrk** [comment]
I don't have time right now, but I may be able to next week if nobody else gets to it.

**Comment by looooo** [comment]
I just tested this locally and I still get this error for the pastix-feedstock:
```
Make Error at CMakeLists.txt:455 (message):
  PASTIX_INT64 is enabled and provided Scotch is not compiled with int64
  support, please build with -DPASTIX_INT64=OFF or install a 64 bits version
  of Scotch.
```
So my proposal does not fix https://github.com/conda-forge/scotch-feedstock/issues/88

**Comment by Tobias-Fischer** [comment]
Looking at their install instructions, I don't think setting any flags is necessary:
https://gitlab.inria.fr/scotch/scotch/-/blob/master/INSTALL.txt?ref_type=heads#L380-386

Are you happy if we remove these changes and merge the pull request so we bump version to 7.0.5 @looooo?

**Comment by Tobias-Fischer** [comment]
Should we merge here @conda-forge/scotch ?

**Comment by minrk** [comment]
Thank you, @looooo!

**Comment by moorepants** [comment]
I'm getting failers on mac ci runs today with this error:

```
E   ImportError: dlopen(/Users/runner/miniconda3/envs/test/lib/python3.9/site-packages/ipopt_wrapper.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_SCOTCH_errorPrint'
```

From this PR: https://github.com/csu-hmc/opty/pull/253

**Comment by Tobias-Fischer** [comment]
Can you please create an issue and fill the template?

**Pull request merged**
