### PR TITLE
Update ptscotch to 6.0.5

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by minrk** [comment]
Everything worked but openmpi + mac. I pushed a likely fix.

**Comment by dalcinl** [comment]
Still failing openmpi+mac. Let's try reducing the number of processes. If that does not work, I'll just comment out the `make ptcheck` line.

**Comment by dalcinl** [comment]
@minrk I don't think 47d975e is needed at all. Look the `test` section in the recipe, note the dependency on `toolchain`, that should set the rpath in `LDFLAGS`. Anyway, your commit does not introduce any harm, so I'm ok with letting it be. Please merge this PR if everything is OK on your side.

**Comment by minrk** [comment]
@dalcinl without 47d975e, the test program fails to start due to a failure to load libmpi, so I think it's required.

Should be all set, though.

**Pull request merged**
