### PR TITLE
Build ptscotch with conda-build 3 outputs

### PR DESCRIPTION
**Pull request by minrk**
instead of a separate branch, which won't get autotick-bot PRs, etc.

### CODE REVIEW

**Comment by minrk** [comment]
This means we can delete the `ptscotch` branch instead of having to keep it in sync

**Comment by basnijholt** [comment]
IIUC this means that there won't be a non parallel scotch?

Remembering https://github.com/conda-forge/mumps-feedstock/issues/21 and https://github.com/conda-forge/mumps-feedstock/pull/22 this seems like a bad idea.

But maybe I don't follow what's happening in this PR though.

**Comment by basnijholt** [comment]
Cool, this will make it simpler! 🥇

**Comment by minrk** [comment]
I'm going to have a look at a similar patch for mumps next.

**Pull request merged**
